# Generated by Django 3.2.4 on 2021-09-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_kor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beer_eng_name', models.CharField(blank=True, max_length=255, null=True)),
                ('beerPhotoPath', models.CharField(blank=True, max_length=255, null=True)),
                ('beer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('aroma', models.FloatField(blank=True, null=True)),
                ('appearance', models.FloatField(blank=True, null=True)),
                ('flavor', models.FloatField(blank=True, null=True)),
                ('mouthfeel', models.FloatField(blank=True, null=True)),
                ('types', models.ManyToManyField(to='beers.Type')),
            ],
        ),
    ]
