# Generated by Django 3.2.1 on 2021-09-30 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beers', '0003_beer_like_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='like_users',
            field=models.ManyToManyField(related_name='like_beers', through='beers.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
