# Generated by Django 3.2.1 on 2021-10-02 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211001_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_friends',
            field=models.ManyToManyField(related_name='take_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
