# Generated by Django 3.2.4 on 2021-10-01 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211001_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='add_friends',
            field=models.ManyToManyField(related_name='take_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
