# Generated by Django 3.2.1 on 2021-10-05 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_add_friends'),
        ('users', '0003_auto_20211003_0521'),
    ]

    operations = [
    ]
