# Generated by Django 3.2.1 on 2021-10-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20211005_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhotoPath',
            field=models.ImageField(blank=True, max_length=505, null=True, upload_to='profiles/%Y/%m/%d/'),
        ),
    ]
