beer_list = {
    # "1664블랑": "Kronenbourg 1664 Blanc",
    # "경복궁": "Kabrew Gyeongbokgung Royal Pride IPA",
    # "광화문": "ARK Seoulite Ale",
    # "구미호 IPA": "Kabrew Kumiho India Pale Ale",
    # "구미호 피치 에일": "Kabrew Kumiho Peach Ale",
    # "구스 아일랜드 IPA" : "Goose Island Goose IPA",
    # "구스 아일랜드 덕덕구스 " : "Goose Island Duck Duck Goose",
    # "구스 아일랜드 마틸다" : "Goose Island Matilda",
    # "구스 아일랜드 버본 컨트리 스타우트" : "Goose Island Bourbon County Stout",
    # "구스 아일랜드 소피" : "Goose Island Sofie",
    # "구스 아일랜드 썸머 타임" : "Goose Island Summertime",
    # "구스 아일랜드 페페 네로" : "Goose Island Pepe Nero",
    # "구스 아일랜드 혼커스 에일" : "Goose Island Honkers Ale",
    # "구스 아일랜드 312" : "Goose Island 312 Urban Wheat Ale",
    # "기네스 드라우트" : "Guinness Draught",
    # "기네스 엑스트라 스타우트(북미)" : "Guinness Extra Stout (North America)",
    # "기네스 엑스트라 스타우트(세계)" : "Guinness Foreign Extra Stout",
    # "기네스 흑맥주" : "Guinness Black Lager",
    # "기린 라거" : "Kirin Lager",
    # "기린 이치방" : "Kirin Ichiban",
    # "남산" : "Kabrew Namsan Mountain Premium Citra Ale",
    # "버드와이저" : "Budweiser",
    # "버드와이저 셀렉트" : "Budweiser Select",
    # "부드바이저 부드바" : "Budweiser Budvar",
    # "부드바이저 부드바 흑맥주" : "Budweiser Budvar Dark",
    # "비너스" : "Cyprus Venus",
    # "데스페라도스" : "Desperados",
    # "데스페라도스 레드" : "Desperados Red",
    # "드라이 D" : "Hite D (Dry Finish)",
    # "라구니타스 IPA" : "Lagunitas India Pale Ale (IPA)",
    # "라구니타스 데이타임" : "Lagunitas DayTime",
    # "라구니타스 막시무스" : "Lagunitas Maximus IPA",
    # "라오산 4.0" : "Tsingtao Laoshan 4.0% 10°P",
    # "라오산 4.7" : "Tsingtao Laoshan 4.7% 11°P",
    # "레페 브라운" : "Leffe Brune",
    # "망고 링고" : "Mango Lingo",
    # "맥스" : "Hite Prime Max",
    # "매그너스 쥬시 애플" : "Magners Juicy Apple",
    # "밀러 드래프트" : "Miller Genuine Draft (MGD)",
    # "밀러 라이트" : "Miller Lite",
    # "밀러 칠 체라다 스타일" : "Miller Chill Chelada Style",
    # "밀러 하이 라이프" : "Miller High Life",
    # "산미구엘페일필젠" : "San Miguel Pale Pilsen",
    # "삿포로" : "Sapporo Draft Beer",
    # "삿포로 리저브" : "Sapporo Reserve",
    # "삿포로 프리미엄" : "Sapporo premium lager",
    # "산토리" : "Suntory The Premium Malt's",
    # "산토리카오루에일" : "Suntory The Premium Malt's Kaoru Ale",
    # "슈파텐 뮌헨" : "Spaten Münchner München",
    # "슈파텐 옥토버페스트" : "Spaten Oktoberfest Ur-Märzen",
    # "슈파텐 옵티메이터" : "Spaten Optimator",
    # "스텔라 아르투아" : "Stella Artois",
    # "싱하" : "Singha Draft",
    # "써머스비 애플" : "Somersby Apple Cider",
    # "바르슈타이너" : "Warsteiner Premium Verum",
    # "바르슈타이너 던켈" : "Warsteiner Premium Dunkel",
    # "벡스" : "Beck's",
    # "벡스 흑맥주" : "Beck's Dark",
    # "브루독 펑크 AF" : "BrewDog Punk AF",
    # "브루독 펑크 IPA" : "BrewDog Punk IPA (5.6%)",
    # "블루문" : "Blue Moon Belgian White",
    # "아사히 슈퍼 드라이" : "Asahi Super Dry",
    # "아사히 드라이 블랙" : "Asahi Super Dry Black",
    # "아사히 프라임 리치" : "Asahi Clear Prime Rich",
    # "애플 폭스" : "Apple Fox",
    # "에델바이스 스노우프레쉬" : "Edelweiss Weissbier Snowfresh",
    # "에딩거 바이스비어" : "Erdinger Weissbier",
    # "예비스" : "Sapporo Yebisu",
    # "이슬 톡톡" : "Isul Tok Tok",
    # "이슬 톡톡 파인애플" : "Isul Tok Tok Pineapple",
    # "스타우트" : "Hite Black Beer Stout",
    # "예거 라들러 레몬" : "Egger Naturtrüber Zitronenradler",
    # "예거 라들러 자몽" : "Egger Grapefruit Radler",
    # "제주 백록담" : "Jeju Baengnokdam Ale",
    # "제주 성산일출봉" : "Jeju Seongsan Ilchulbong Ale",
    # "제주 위트 에일" : "Jeju Wit Ale",
    # "제주 펠롱 에일" : "Jeju Pellong Ale",
    # "카스 라이트" : "Cass Light",
    # "카스 프레쉬" : "Cass Fresh",
    # "칼스버그" : "Carlsberg Pilsner",
    # "코로나" : "Corona Extra",
    # "코로나 라이트" : "Corona Light",
    # "코젤 다크" : "Kozel Černý (Dark) 10°",
    # "코젤 라거" : "Kozel Premium Lager 12°",
    # "퀸즈 에일 블론드" : "Queen's Ale Blonde Type",
    # "퀸즈 에일 엑스트라 비터" : "Queen's Ale Extra Bitter Type",
    # "클라우드" : "Kloud Original Gravity",
    # "타이거" : "Tiger Beer",
    # "타이거 라들러 레몬" : "Tiger Radler Lemon",
    # "테라" : "Terra",
    # "칭따오" : "Tsingtao",
    # "칭따오 위트" : "Tsingtao Wheat Beer",
    # "칭따오 퓨어 드래프트" : "Tsingtao Draft Beer 11º (Pure Draft Beer)",
    # "파울라너 오리지널 뮌헨" : "Paulaner Original Münchner Hell (Premium Lager)",
    # "파울라너 옥토버페스트 맥주" : "Paulaner Oktoberfest Bier (Wiesn Bier)",
    # "파울라너 살베이터" : "Paulaner Salvator",
    # "파울라너 헤페 바이스비어" : "Paulaner Hefe-Weissbier",
    # "파타고니아" : "Patagonia",
    # "파타고니아 앰버 라거" : "Patagonia Amber Lager",
    # "파타고니아 바이스" : "Patagonia Weisse",
    # "파타고니아 보헤미안 필스너" : "Patagonia Bohemian Pilsener",
    # "페로니" : "Peroni",
    # "필굿" : "Happoshu Filgood",
    # "필라이트" : "FiLite",
    # "필라이트 후레쉬" : "Filite Fresh Cool & Clear",
    # "필라이트 바이젠" : "Filite Weizen",
    # "필스너 우르켈" : "Pilsner Urquell",
    # "핏츠" : "Fitz Super Clear",
    # "하얼빈" : "Harbin Beer",
    # "하이네켄" : "Heineken",
    # "하이네켄 논알코올" : "Heineken 0.0",
    # "하이네켄 다크라거" : "Heineken Dark Lager",
    # "하이트" : "Hite Beer",
    # "하이트 엑스트라 콜드" : "Hite Extra Cold",
    # "하이트 제로" : "Hite Zero",
    # "호가든" : "Hoegaarden",
    # "호가든 로제" : "Hoegaarden Rosée",
    # "홉 하우스 13" : "Hop House 13 Lager",
    # "홉탄두 IPA" : "Kabrew Hoptandu IPA",

}