# Generated by Django 3.2.1 on 2021-10-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feedPhotoPath',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='feeds/%Y/%m/%d/'),
        ),
    ]
