# Generated by Django 3.2.4 on 2021-09-28 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=3)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='beers.beer')),
            ],
        ),
    ]
