# Generated by Django 3.2.4 on 2021-10-01 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_alter_beer_like_users'),
        ('boards', '0003_remove_board_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='nickname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.beer'),
        ),
    ]
